const mongoose = require('mongoose');

const salarySchema = new mongoose.Schema({
  year: Number,
  month: Number,
  salaryState: String,
  isLocked: Boolean,
  baseSalary: Number,
  marriageAllowance: Number,
  transportAllowance: Number,
  serviceYearsAllowance: Number,
  educationAllowance: Number,
  bonuses: Number,
  otherAllowances: Number,
  totalAllowances: Number,
  socialSecurity: Number,
  absence: Number,
  absenceDays: Number,
  salaryPaidDate: String,
  lateHours: Number,
  lateHoursDeduction: Number,
  loan: Number,
  otherDeductions: Number,
  totalDeductions: Number,
  vacationDays: Number,
  vacationDaysDeduction: Number,
  netSalary: Number,
  notes: String,
});

const employeeSchema = new mongoose.Schema({
  name: String,
  docID: String,
  empState: String,
  schoolName: String,
  email: String,
  empPhoneNumber: String,
  jobTitle: String,
  education: String,
  startDate: String,
  iban: String,
  swift: String,
  empToken: String,
  baseSalary: Number,
  marriageState: String,
  marriageAllowance: Number,
  transportAllowance: Number,
  serviceYearsAllowance: Number,
  educationAllowance: Number,
  bonuses: Number,
  otherAllowances: Number,
  totalAllowances: Number,
  socialSecurity: Number,
  absence: Number,
  absenceDays: Number,
  loan: Number,
  lateHours: Number,
  lateHoursDeductions: Number,
  otherDeductions: Number,
  totalDeductions: Number,
  vacationDays: Number,
  vacationDaysDeductions: Number,
  netSalary: Number,
  notes: String,
  salaryHistory: [salarySchema], // إضافة سجل الرواتب هنا
});

module.exports = mongoose.model('Employee', employeeSchema);
